/*
 * This source file was generated by the Gradle 'init' task
 */
package smartosc.jsc.applications;

import smartosc.jsc.applications.etl.ETL;
import smartosc.jsc.applications.etl.mo_commanders.CommanderCreation;
import smartosc.jsc.applications.etl.mo_commanders.TransformerCommand;

import java.util.List;

public class App {
    public static void main(String[] args) {
        System.out.println("==========================START ETL APPLICATION =========================");

        String configs = "{\"nodes\":{" +
                "\"1\":{\"id\":1,\"name\":\"RENAME_COLUMNS\",\"config\":[{\"oldColumnName\":\"title\",\"newColumnName\":\"name\"}],\"parent\":null}," +
                "\"2\":{\"id\":2,\"name\":\"CONCAT\",\"config\":[{\"newColumnName\":\"sku_country\",\"concatColumns\":\"sku,country\",\"delimiter\":\"_\"}],\"parent\":1}," +
                "\"3\":{\"id\":3,\"name\":\"REMOVE_COLUMNS\",\"config\":[{\"column\":\"image\"}],\"parent\":2}," +
                "\"4\":{\"id\":4,\"name\":\"FILTER\",\"config\":[{\"column\":\"country\",\"value\":\"VN\",\"operator\":\"EQ\"}],\"parent\":3}," +
                "\"5\":{\"id\":5,\"name\":\"FILTER\",\"config\":[{\"column\":\"category\",\"value\":\"Soundbar\",\"operator\":\"EQ\"}],\"parent\":3}," +
                "\"6\":{\"id\":6,\"name\":\"ADD_COLUMNS\",\"config\":[{\"column\":\"salable\",\"value\":\"Y\"}],\"parent\":4}," +
                "\"7\":{\"id\":7,\"name\":\"ADD_COLUMNS\",\"config\":[{\"column\":\"salable\",\"value\":\"N\"}],\"parent\":5}," +
                "\"8\":{\"id\":8,\"name\":\"UNION\",\"config\":[{\"nodeIds\":\"6,7\"}],\"parent\":null}" +
                "}}";
        String dataset = "[" +
                "{\"sku\":\"EXAM.SKU.01\",\"title\":\"Smart Tivi 4K\",\"width\":120,\"height\":40,\"category\":\"TIVI\",\"image\":\"https://lg.com/sku/1\",\"country\":\"VN\"}," +
                "{\"sku\":\"EXAM.SKU.02\",\"title\":\"Smart Tivi 4K Untra Width\",\"width\":120,\"height\":40,\"category\":\"TIVI\",\"image\":\"https://lg.com/sku/2\",\"country\":\"VN\"}," +
                "{\"sku\":\"EXAM.SKU.03\",\"title\":\"Smart Tivi 2K\",\"width\":120,\"height\":40,\"category\":\"TIVI\",\"image\":\"https://lg.com/sku/3\",\"country\":\"VN\"}," +
                "{\"sku\":\"EXAM.SKU.04\",\"title\":\"Smart Tivi 2K Untra Width\",\"width\":120,\"height\":40,\"category\":\"TIVI\",\"image\":\"https://lg.com/sku/4\",\"country\":\"VN\"}," +
                "{\"sku\":\"EXAM.SKU.05\",\"title\":\"Smart Tivi 8K\",\"width\":120,\"height\":40,\"category\":\"TIVI\",\"image\":\"https://lg.com/sku/5\",\"country\":\"VN\"}," +
                "{\"sku\":\"EXAM.SKU.06\",\"title\":\"Smart Tivi 8K Untra Width\",\"width\":120,\"height\":40,\"category\":\"TIVI\",\"image\":\"https://lg.com/sku/6\",\"country\":\"VN\"}," +
                "{\"sku\":\"EXAM.SKU.07\",\"title\":\"Projector 4K\",\"width\":20,\"height\":30,\"category\":\"Projector\",\"image\":\"https://lg.com/sku/7\",\"country\":\"VN\"}," +
                "{\"sku\":\"EXAM.SKU.08\",\"title\":\"Projector 4K Untra Width\",\"width\":20,\"height\":30,\"category\":\"Projector\",\"image\":\"https://lg.com/sku/8\",\"country\":\"VN\"}," +
                "{\"sku\":\"EXAM.SKU.09\",\"title\":\"Projector 2K\",\"width\":20,\"height\":30,\"category\":\"Projector\",\"image\":\"https://lg.com/sku/9\",\"country\":\"VN\"}," +
                "{\"sku\":\"EXAM.SKU.10\",\"title\":\"Projector 2K Untra Width\",\"width\":20,\"height\":30,\"category\":\"Projector\",\"image\":\"https://lg.com/sku/10\",\"country\":\"VN\"}," +
                "{\"sku\":\"EXAM.SKU.11\",\"title\":\"Projector 8K\",\"width\":20,\"height\":30,\"category\":\"Projector\",\"image\":\"https://lg.com/sku/11\",\"country\":\"VN\"}," +
                "{\"sku\":\"EXAM.SKU.12\",\"title\":\"Projector 8K Untra Width\",\"width\":20,\"height\":30,\"category\":\"Projector\",\"image\":\"https://lg.com/sku/12\",\"country\":\"VN\"}," +
                "{\"sku\":\"EXAM.SKU.13\",\"title\":\"Soundbar Bluetooth A\",\"width\":140,\"height\":15,\"category\":\"Soundbar\",\"image\":\"https://lg.com/sku/13\",\"country\":\"UK\"}," +
                "{\"sku\":\"EXAM.SKU.14\",\"title\":\"Soundbar Bluetooth A\",\"width\":140,\"height\":15,\"category\":\"Soundbar\",\"image\":\"https://lg.com/sku/14\",\"country\":\"UK\"}," +
                "{\"sku\":\"EXAM.SKU.15\",\"title\":\"Soundbar Bluetooth A\",\"width\":140,\"height\":15,\"category\":\"Soundbar\",\"image\":\"https://lg.com/sku/15\",\"country\":\"UK\"}," +
                "{\"sku\":\"EXAM.SKU.16\",\"title\":\"Soundbar Bluetooth A\",\"width\":140,\"height\":15,\"category\":\"Soundbar\",\"image\":\"https://lg.com/sku/16\",\"country\":\"UK\"}," +
                "{\"sku\":\"EXAM.SKU.17\",\"title\":\"Soundbar Bluetooth A\",\"width\":140,\"height\":15,\"category\":\"Soundbar\",\"image\":\"https://lg.com/sku/17\",\"country\":\"VN\"}," +
                "{\"sku\":\"EXAM.SKU.18\",\"title\":\"Soundbar Bluetooth A\",\"width\":140,\"height\":15,\"category\":\"Soundbar\",\"image\":\"https://lg.com/sku/18\",\"country\":\"VN\"}," +
                "{\"sku\":\"EXAM.SKU.19\",\"title\":\"Soundbar Bluetooth A\",\"width\":140,\"height\":15,\"category\":\"Soundbar\",\"image\":\"https://lg.com/sku/19\",\"country\":\"VN\"}," +
                "{\"sku\":\"EXAM.SKU.20\",\"title\":\"Soundbar Bluetooth A\",\"width\":140,\"height\":15,\"category\":\"Soundbar\",\"image\":\"https://lg.com/sku/20\",\"country\":\"VN\"}," +
                "{\"sku\":\"EXAM.SKU.21\",\"title\":\"Soundbar Bluetooth A\",\"width\":140,\"height\":15,\"category\":\"Soundbar\",\"image\":\"https://lg.com/sku/21\",\"country\":\"VN\"}," +
                "{\"sku\":\"EXAM.SKU.22\",\"title\":\"Soundbar Bluetooth A\",\"width\":140,\"height\":15,\"category\":\"Soundbar\",\"image\":\"https://lg.com/sku/22\",\"country\":\"VN\"}]";
        try {
            CommanderCreation commanderCreation = new CommanderCreation();
            List<TransformerCommand> commands = commanderCreation.buildCommandQueue(configs);

            ETL etl = new ETL();
            etl.execute(dataset, commands);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }

        System.out.println("==========================END ETL APPLICATION =========================");
    }
}
