/*
 * This source file was generated by the Gradle 'init' task
 */
package smartosc.jsc.applications;

import smartosc.jsc.applications.ecommerce.orders.services.IOrderService;
import smartosc.jsc.applications.ecommerce.orders.services.OrderService;
import smartosc.jsc.applications.ecommerce.products.services.IProductService;
import smartosc.jsc.applications.ecommerce.products.services.ProductService;
import smartosc.jsc.applications.ecommerce.promotion.services.IPromotionService;
import smartosc.jsc.applications.ecommerce.promotion.services.PromotionService;

import java.util.Scanner;

public class EcommerceApp {
    public static final String folderPath = "resources";
    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);
        IProductService productService = new ProductService(scanner, folderPath);
        IOrderService orderService = new OrderService(scanner, folderPath);
        IPromotionService promotionService = new PromotionService(scanner, folderPath);

        while (true) {
            System.out.println("\nE-Commerce Application");
            System.out.println("1. Manage Products");
            System.out.println("2. Manage Orders");
            System.out.println("3. Manage Promotion");
            System.out.println("4. Exit");
            System.out.print("Choose an option: ");

             int choice = scanner.nextInt();
             scanner.nextLine();

            switch (choice) {
                case 1 -> productService.manageProducts();
                case 2 -> orderService.manageOrders();
                case 3 -> promotionService.managePromotions();
                case 4 -> {
                    System.out.println("Exiting application. Goodbye!");
                    return;
                }
                default -> System.out.println("Invalid option. Please try again.");
            }
        }
    }
}
