/*
 * This source file was generated by the Gradle 'init' task
 */
package smartosc.jsc.applications;

public class User {
    public Integer userId;
    public String fullname;
    public String email;
}
