/*
 * This source file was generated by the Gradle 'init' task
 */
package smartosc.jsc.applications;

import org.junit.jupiter.api.Test;

class AppTest {
    @Test
    void appHasAGreeting() {

    }
}
