/*
 * This source file was generated by the Gradle 'init' task
 */
package smartosc.jsc.applications.promotion.action;

import java.util.ArrayList;
import java.util.List;

import org.json.JSONArray;
import org.json.JSONObject;

import smartosc.jsc.applications.promotion.Promotion;
import smartosc.jsc.applications.promotion.promotioninterface.PromotionRepositoryInterface;

public class PromotionRepository implements PromotionRepositoryInterface {
    @Override
    public void addPromotion(String jsonString) {
        JSONArray jsonArray = new JSONArray(jsonString);
        List<Promotion> promotions = new ArrayList<>();

        for (int i = 0; i < jsonArray.length(); i++) {
            JSONObject jsonObject = jsonArray.getJSONObject(i);
            int id = jsonObject.getInt("id");
            String name = jsonObject.getString("name");
            String type = jsonObject.getString("type");
            double discount = jsonObject.getDouble("discount");
            String condition = jsonObject.getJSONObject("condition").toString();
            String description = jsonObject.getString("description");
            String code = jsonObject.getString("code");

            promotions.add(new Promotion(id, name, type, discount, condition, description, code));
        }

        Promotion.writeToCSV(promotions, Promotion.FILE_NAME);

        System.out.println("Promotions added successfully.");
    }

    public static Promotion getPromotionByCode(String promotionCode) {
        String fileName = Promotion.FILE_NAME;
        List<Promotion> promotions = Promotion.readPromotionsFromCSV(fileName);
        for (Promotion promo : promotions) {
            if (promo.code.equals(promotionCode)) {
                return promo;
            }
        }

        return null;
    }
}