/*
 * This source file was generated by the Gradle 'init' task
 */
package smartosc.jsc.applications.promotion.action;

import java.util.List;

import org.json.JSONObject;

import smartosc.jsc.applications.promotion.Promotion;

public class ValidatePromotion {
    public static boolean validatePromotion(String promotionCode, double purchase) {
        String fileName = Promotion.FILE_NAME;
        List<Promotion> promotions = Promotion.readPromotionsFromCSV(fileName);
        
        for (Promotion promo : promotions) {
            if (promo.code.equals(promotionCode)) {
                try {
                    JSONObject conditionObj = new JSONObject(promo.condition);
                    int minPurchase = conditionObj.getInt("minPurchase");
                    if (purchase >= minPurchase) {
                        System.out.println("Promotion " + promo.name + " can be applied. Discount: " + promo.discount);
                    } else {
                        System.out.println("Promotion " + promo.name + " cannot be applied. Minimum purchase required: " + minPurchase);
                    }
                    return true;
                } catch (Exception e) {
                    System.out.println("Error while processing promotion " + promo.name + ": " + e.getMessage());
                }
            }
        }

        return false;
    }
}