/*
 * This source file was generated by the Gradle 'init' task
 */
package smartosc.jsc.applications.order.orderinterface;

import java.io.IOException;

import smartosc.jsc.applications.cart.Cart;

public interface OrderRepositoryInterface {
    void saveOrder(Cart cart, String filePath) throws IOException;
}