/*
 * This source file was generated by the Gradle 'init' task
 */
package smartosc.jsc.applications.product;

import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.util.List;

public class Product {
    public int id;
    public String name;
    public double price;
    public int quantity;
    public String description;

    public Product(int id, String name, double price, int quantity, String description) {
        this.id = id;
        this.name = name;
        this.price = price;
        this.quantity = quantity;
        this.description = description;
    }

    public int getId() {
        return id;
    }

    public String getName() {
        return name;
    }

    public double getPrice() {
        return price;
    }

    public int getQuantity() {
        return quantity;
    }

    public String getDescription() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public void setPrice(double price) {
        this.price = price;
    }

    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public static void writeToCSV(List<Product> products, String fileName) {
        try (BufferedWriter writer = new BufferedWriter(new FileWriter(fileName))) {
            writer.write("id,name,price,quantity,description");
            writer.newLine();

            for (Product product : products) {
                writer.write(product.id + "," + product.name + "," + product.price + "," + product.quantity + "," + product.description);
                writer.newLine();
            }

            System.out.println("Data written to " + fileName + " successfully.");
        } catch (IOException e) {
            System.out.println("Error writing to file: " + e.getMessage());
        }
    }
}