/*
 * This source file was generated by the Gradle 'init' task
 */
package smartosc.jsc.applications.order.action;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.FileWriter;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.io.IOException;

import smartosc.jsc.applications.order.Order;
import smartosc.jsc.applications.order.orderinterface.OrderRepositoryInterface;
import smartosc.jsc.applications.cart.Cart;

public class OrderRepository implements OrderRepositoryInterface {

    @Override
    public void saveOrder(Cart cart, String filePath) throws IOException {
        try (FileWriter writer = new FileWriter(filePath, true)) {
            writer.append(String.valueOf(cart.getId())).append(",")
                  .append(String.valueOf(cart.getGrandTotal())).append(",")
                  .append(String.valueOf(cart.getDiscount())).append(",")
                  .append(cart.getCouponCode()).append(",")
                  .append(String.valueOf(cart.getQuantity())).append(",")
                  .append(cart.getCustomerEmail()).append("\n");
        } catch (IOException e) {
            System.err.println("Error saving cart: " + e.getMessage());
            throw e;
        }
    }
}