/*
 * This source file was generated by the Gradle 'init' task
 */
package smartosc.jsc.applications.order.ordertitems;

public class OrderItem {
    public int id;
    public int orderId;
    public double grandTotal;
    public String productId;
    public double productPrice;
    public int quantity;

    // Default constructor
    public OrderItem() {}

    // Parameterized constructor
    public OrderItem(int id, int orderId, double grandTotal, String productId, double productPrice, int quantity) {
        this.id = id;
        this.orderId = orderId;
        this.grandTotal = grandTotal;
        this.productId = productId;
        this.productPrice = productPrice;
        this.quantity = quantity;
    }

    // Getter and Setter methods
    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public int getOrderId() {
        return orderId;
    }

    public void setOrderId(int orderId) {
        this.orderId = orderId;
    }

    public double getGrandTotal() {
        return grandTotal;
    }

    public void setGrandTotal(double grandTotal) {
        this.grandTotal = grandTotal;
    }

    public String getProductId() {
        return productId;
    }

    public void setProductId(String productId) {
        this.productId = productId;
    }

    public double getProductPrice() {
        return productPrice;
    }

    public void setProductPrice(double productPrice) {
        this.productPrice = productPrice;
    }

    public int getQuantity() {
        return quantity;
    }

    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }
}