/*
 * This source file was generated by the Gradle 'init' task
 */
package smartosc.jsc.applications.order;

public class Order {
    private int id;
    private double grandTotal;
    private double discount;
    private String couponCode;
    private int quantity;
    private String customerEmail;

    // Constructor
    public Order(int id, double grandTotal, double discount, String couponCode, int quantity, String customerEmail) {
        this.id = id;
        this.grandTotal = grandTotal;
        this.discount = discount;
        this.couponCode = couponCode;
        this.quantity = quantity;
        this.customerEmail = customerEmail;
    }

    // Default Constructor
    public Order() {}

    // Getter and Setter methods
    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public double getGrandTotal() {
        return grandTotal;
    }

    public void setGrandTotal(double grandTotal) {
        this.grandTotal = grandTotal;
    }

    public double getDiscount() {
        return discount;
    }

    public void setDiscount(double discount) {
        this.discount = discount;
    }

    public String getCouponCode() {
        return couponCode;
    }

    public void setCouponCode(String couponCode) {
        this.couponCode = couponCode;
    }

    public int getQuantity() {
        return quantity;
    }

    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }

    public String getCustomerEmail() {
        return customerEmail;
    }

    public void setCustomerEmail(String customerEmail) {
        this.customerEmail = customerEmail;
    }

    @Override
    public String toString() {
        return "Order{" +
                "id=" + id +
                ", grandTotal=" + grandTotal +
                ", discount=" + discount +
                ", couponCode='" + couponCode + '\'' +
                ", quantity=" + quantity +
                ", customerEmail='" + customerEmail + '\'' +
                '}';
    }
}