/*
 * This source file was generated by the Gradle 'init' task
 */
package smartosc.jsc.applications.cart.cartitems;

public class CartItem {
    // Thuộc tính của CartItem
    public int id;
    public int cartId;
    public double grandTotal;
    public String productId;
    public double productPrice;
    public int quantity;

    // Constructor không tham số
    public CartItem() {
        // Khởi tạo giá trị mặc định nếu cần
        this.id = 0;
        this.cartId = 0;
        this.grandTotal = 0.0;
        this.productId = "";
        this.productPrice = 0.0;
        this.quantity = 0;
    }

    // Constructor có tham số để khởi tạo giá trị ban đầu
    public CartItem(int id, int cartId, double grandTotal, String productId, double productPrice, int quantity) {
        this.id = id;
        this.cartId = cartId;
        this.grandTotal = grandTotal;
        this.productId = productId;
        this.productPrice = productPrice;
        this.quantity = quantity;
    }

    // Getter và Setter cho các thuộc tính
    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public int getCartId() {
        return cartId;
    }

    public void setCartId(int cartId) {
        this.cartId = cartId;
    }

    public double getGrandTotal() {
        return grandTotal;
    }

    public void setGrandTotal(double grandTotal) {
        this.grandTotal = grandTotal;
    }

    public String getProductId() {
        return productId;
    }

    public void setProductId(String productId) {
        this.productId = productId;
    }

    public double getProductPrice() {
        return productPrice;
    }

    public void setProductPrice(double productPrice) {
        this.productPrice = productPrice;
    }

    public int getQuantity() {
        return quantity;
    }

    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }

    // Phương thức tính grandTotal của một sản phẩm trong giỏ hàng
    public double calculateTotal() {
        return productPrice * quantity;
    }

    public void displayCartItemInfo() {
        System.out.println("CartItem ID: " + id);
        System.out.println("Product ID: " + productId);
        System.out.println("Price: " + productPrice);
        System.out.println("Quantity: " + quantity);
        System.out.println("Total: " + grandTotal);
    }
}