/*
 * This source file was generated by the Gradle 'init' task
 */
package smartosc.jsc.applications.promotion.promotioninterface;

public interface PromotionRepositoryInterface {
    void addPromotion(String jsonString);
}