/*
 * This source file was generated by the Gradle 'init' task
 */
package smartosc.jsc.applications.cart.action;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import smartosc.jsc.applications.cart.Cart;
import smartosc.jsc.applications.cart.cartinterface.CartRepositoryInterface;
import smartosc.jsc.applications.cart.cartitems.CartItem;

public class CartRepository implements CartRepositoryInterface {

    private Map<Integer, Cart> cartMap = new HashMap<>();
    private Map<Integer, List<CartItem>> cartItemsMap = new HashMap<>();
    private int nextCartId = 1;

    public void addProductToCart(String productId, int quantity, double price) {
        int cartId = nextCartId++;

        Cart cart = cartMap.get(cartId);
        if (cart == null) {
            cart = new Cart(cartId);
            cartMap.put(cartId, cart);
        }

        CartItem cartItem = new CartItem();
        cartItem.setId(cartItemsMap.get(cartId) == null ? 1 : cartItemsMap.get(cartId).size() + 1);
        cartItem.setCartId(cartId);
        cartItem.setProductId(productId);
        cartItem.setProductPrice(price);
        cartItem.setQuantity(quantity);
        cartItem.setGrandTotal(cartItem.calculateTotal());

        cartItemsMap.computeIfAbsent(cartId, k -> new ArrayList<>()).add(cartItem);

        cart.setGrandTotal(cart.getGrandTotal() + cartItem.getGrandTotal());
        cart.setQuantity(cart.getQuantity() + quantity);

        cartMap.put(cartId, cart);
    }

    @Override
    public Cart getCartById(int cartId) {
        return cartMap.get(cartId);
    }

    @Override
    public List<CartItem> getCartItems(int cartId) {
        return cartItemsMap.getOrDefault(cartId, new ArrayList<>());
    }
}