/*
 * This source file was generated by the Gradle 'init' task
 */
package smartosc.jsc.applications.promotion;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

public class Promotion {
    public static final String FILE_NAME = "promotion.csv";
    public int id;
    public String name;
    public String type;
    public double discount;
    public String condition;
    public String description;
    public String code;

    public Promotion(int id, String name, String type, double discount, String condition, String description, String code) {
        this.id = id;
        this.name = name;
        this.type = type;
        this.discount = discount;
        this.condition = condition;
        this.description = description;
        this.code = code;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public double getDiscount() {
        return discount;
    }

    public void setDiscount(double discount) {
        this.discount = discount;
    }

    public String getCondition() {
        return condition;
    }

    public void setCondition(String condition) {
        this.condition = condition;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public static void writeToCSV(List<Promotion> promotions, String fileName) {
        try (BufferedWriter writer = new BufferedWriter(new FileWriter(fileName))) {
            // Ghi header vào file CSV
            writer.write("id,name,type,discount,condition,description,code");
            writer.newLine();

            // Ghi dữ liệu của từng Promotion vào file CSV
            for (Promotion promo : promotions) {
                writer.write(promo.id + "," + promo.name + "," + promo.type + "," + promo.discount + "," + promo.condition + "," + promo.description + "," + promo.code);
                writer.newLine();
            }

            System.out.println("Data written to " + fileName + " successfully.");
        } catch (IOException e) {
            System.out.println("Error writing to file: " + e.getMessage());
        }
    }

    public static List<Promotion> readPromotionsFromCSV(String fileName) {
        List<Promotion> promotions = new ArrayList<>();
        try (BufferedReader reader = new BufferedReader(new FileReader(fileName))) {
            String line;
            while ((line = reader.readLine()) != null) {
                if (line.startsWith("id,name")) continue;

                String[] columns = line.split(",");
                int id = Integer.parseInt(columns[0]);
                String name = columns[1];
                String type = columns[2];
                double discount = Double.parseDouble(columns[3]);
                String condition = columns[4];
                String description = columns[5];
                String code = columns[6];

                promotions.add(new Promotion(id, name, type, discount, condition, description, code));
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
        
        return promotions;
    }
}