/*
 * This source file was generated by the Gradle 'init' task
 */
package smartosc.jsc.applications.product.productinterface;

import java.util.List;

import smartosc.jsc.applications.product.Product;

public interface ProductRepositoryInterface {
    void addProduct(String jsonString);
    void updateProduct(int id, String name, double price, int quantity, String description);
    void deleteProduct(int id);
    List<Product> getAllProducts();
    List<Product> getListProducts(List<Integer> ids);
    List<Product> filterProductByName(String name);
}